// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGbF9gFXI77ejuzftEQr7FSakGvTy83Fg',
    appId: '1:648610348518:web:01826415520f83b889aa27',
    messagingSenderId: '648610348518',
    projectId: 'school-day-a1e87',
    authDomain: 'school-day-a1e87.firebaseapp.com',
    storageBucket: 'school-day-a1e87.firebasestorage.app',
    measurementId: 'G-Y03W2R42WH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqEEQOEvieCOoUQzVCmoOIX6WWKsfSDLY',
    appId: '1:648610348518:android:a2a05922c07c312e89aa27',
    messagingSenderId: '648610348518',
    projectId: 'school-day-a1e87',
    storageBucket: 'school-day-a1e87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0hBems9SVmQznrVe3J66c4BjtitBEyy4',
    appId: '1:648610348518:ios:5807e7f352eb30ec89aa27',
    messagingSenderId: '648610348518',
    projectId: 'school-day-a1e87',
    storageBucket: 'school-day-a1e87.firebasestorage.app',
    iosBundleId: 'io.cyblox.schoolDay',
  );

}